name: "Release Changelog"
on:
  push:
    tags:
      - "v*"

jobs:
  build-changelog:
    name: "Build Changelog"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "./.github/changelog.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: "v0.1.0"
          toTag: "v0.2.0"

      - name: "Use Changelog"
        run: echo "${{ steps.build_changelog.outputs.changelog }}"