name: "Release Changelog"
on:
  push:
    tags:
      - "v*"

jobs:
  build-changelog:
    name: "Build Changelog"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "./.github/changelog.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: "v1.0.0"
          toTag: "v1.1.0"