name: "Release Changelog"
on:
  push:
    tags:
      - "v*"
      - "stable"

jobs:
  build-changelog:
    permissions:
      id-token: write
      contents: write
      attestations: write
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: Create artifact
        id: artifacts
        shell: bash
        run: |
          echo $(date +"%Y%m%d%H%M") > dist.txt
          echo "New changes:::::::" >> dist.txt
          echo "file_name=dist.txt" >> $GITHUB_OUTPUT
          echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "release_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "./.github/changelog.json"
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: "v0.1.0"
          toTag: "v1.0.0"

      - name: "Use Changelog"
        run: echo "${{ steps.build_changelog.outputs.changelog }}"
   
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.artifacts.outputs.release_name }}
          tag_name: ${{ steps.artifacts.outputs.release_name }}
          prerelease: false
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            ${{ steps.artifacts.outputs.file_name }}
 
